# Site settings
title: Rebecca Cronin-Dixon
email: bbeck410@gmail.com
description: Rebecca Cronin-Dixon Portfolio and Contact Site 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beckcd.com" # the base hostname & protocol for your site
twitter_username: beckcd
github_username: beck410
nss: http://nashvillesoftwareschool.com/
# Build settings
markdown: kramdown
permalink: pretty
collections:
  - projects

