# Site settings
title: All About Beck
email: bbeck410@gmail.com
description: All you need to know about Beck Cronin-Dixon 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://beck410.github.io" # the base hostname & protocol for your site
twitter_username: beckcd
github_username: beck410

# Build settings
markdown: kramdown
highlighter: rouge
